name: t2mobile
description: "Make T2SCHOLA more useful."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  reactive_forms: ^17.0.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2719.3
  custom_refresh_indicator: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter_hooks: ^0.20.5
  reactive_forms_annotations: ^5.0.0
  file_picker: ^8.0.1
  shared_preferences: ^2.2.3
  flutter_inappwebview: ^6.0.0
  html: ^0.15.4
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  collection: ^1.18.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  hooks_riverpod: ^2.5.1
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  drift: ^2.18.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.21
  sqlite3: ^2.4.3
  flutter_widget_from_html_core: ^0.14.12
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  reactive_forms_generator: ^5.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  go_router_builder: ^2.5.1
  retrofit_generator: ^8.1.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  generate: true
